[BasicInfo]
RiverName   = Nan
StationName = N.1
ElemQorH = H
Language = Eng
[FigTime]
BeforeDays = 3
AfterDays  = 11
[GraphRange]
Min_Y1    = 0.0
Max_Y1    = 18.0
MaxV_Y1   = 16.0
Tick_Y1   = 2.0
Min_Rain  = 0
Max_Rain  = 10
MaxV_Rain = 5
Tick_Rain = 1
[PFcondition]
ForecastHyd_WtMean_Flg = 0
;	1:display, 0:Non-display, 2:correct
ForecastHyd_OrgP_Flg = 1
;	1:display, 0:Non-display, 2:correct
ForecastHyd_BestP_Flg = 1
;	1:display, 0:Non-display, 2:correct
AllParticleFlg = 0
;	1:displays all particle, 0:Only result
ForecastRainFlg = 1
;	1:display, 0:Non-display
EnsembleRainFlg = 1
;	1:display, 0:Non-display
BackTimeFlg = 1
;	1:displays for the back time, 0:non-displays for BT
[WarningLevel]
nLevel = 1
Level_1_Value = 7.0
Level_1_Name  = Warning Lv
Level_2_Value = 3.3
Level_2_Name  = Warning Lv3
Level_3_Value = -9999
Level_3_Name  = Warning Lv2
Level_4_Value = 2.6
Level_4_Name  = Warning Lv1
Level_5_Value = -9999
Level_5_Name  = High water level
;   e.g., HighWL/HazardousWL/EvacuationWL/WarningWL/PreWarningWL
[OfflineCalc]
RRIofflineCalc = 1
;	1:display, 0:non-display
OfflineFile = CalcH_offline.csv
[RivSection]
RivSecFlag = 0
;	1:display, 0:non-display
RivSecFile = ObsData/River/SectionXYN.csv
[OthersInfo]
RainJ_dt_min = 30
LegendPosition = 4
;	1:upper left, 2:upper right, 3:center left, 4:center right
